version: '3'
services:
  chatgpt:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatgpt-service:latest
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: C:\Users\Achraf\Desktop\izicap\ChatGPTQA.csv
        target: /app/ChatGPTQA.csv